### ISSUE TITLE
Use the new java producer api

### ISSUE THREAD

**Issue by danstone** [pingles/clj-kafka#45]
http://kafka.apache.org/082/javadoc/index.html?org/apache/kafka/clients/producer/KafkaProducer.html

It would be good to move clj-kafka onto using the new producer, namely I am interested in the callback on ack feature, also it would be nice to surface the future returned by send calls (we could clojureify the payload)

If I get some time I may take a look at this myself if you are accepting pull requests.

Regards

**Comment by danstone** [comment]
I've written a basic library for this, it also includes some more simple consumer stuff over what clj-kafka supplies, again if you are willing to accept pull requests I'm happy to merge this stuff in.

https://github.com/danstone/clafka

**Comment by pingles** [comment]
The ack stuff looks cool- I'll see if I can add support for that as part of doing a heap of other clj-kafka updates :)

**Comment by danstone** [comment]
Excellent work on 0.3.1 :)
