### ISSUE TITLE
clj-kafka.new.producer/producer code error

### ISSUE THREAD

**Issue by pho-coder** [pingles/clj-kafka#57]
(producer config) error
```clojure
([^java.util.Map config]
   (KafkaProducer. config))
```
should be:
```clojure
([^java.util.Map config]
   (KafkaProducer. config (byte-array-serializer) (byte-array-serializer)))
```

now use (producer config) will be:
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Missing required configuration "value.serializer" which has no default value.

**Comment by pingles** [comment]
Hi,

The README has been updated to explicitly pass a serializer. However, config can provide the config value so I think for now this behaviour is fine (use the other arity fn and specify precisely, or, set through config).

Thanks for raising the issue.
