### ISSUE TITLE
Convert Kafka byte-array to String\json

### ISSUE THREAD

**Issue by panda87** [pingles/clj-kafka#67]
Hi All

We are using Kafka for our logging\metrics\events and we found that the metrics (from CollectD) are coming as byte array, and there is no specific function to convert from the byte array to simple String\json, maybe someone here knows about easy way to do that? our consumer is Riemann.

Thanks
D.

**Comment by pingles** [comment]
Hi,

I would suggest map'ing a deserialize function across the sequence of messages- this would take a byte array and return a Clojure data structure.

We've used [Cheshire](https://github.com/dakrone/cheshire), then you probably want something like:

```clojure
(let [ms (messages consumer topic)]
  (map (fn [{:keys [value]}] (parse-json (String. value))) ms)
```

**Comment by pingles** [comment]
The Kafka consumer has support for defining serializers etc. but given messages are just sequences I'd stick with the regular Clojure functions.

Hope that helps, let me know if that doesn't solve the problem you have.

Paul

**Comment by panda87** [comment]
Thanks @pingles i'll check this in the next few days.
One last question, if you are using Riemann - can you tell me how can I create event from the mapping  above and index that?

Thanks!
