### ISSUE TITLE
new producer send callback not invoked

### ISSUE THREAD

**Issue by manuzhang** [pingles/clj-kafka#76]
I tried to print the produced offset with callback like below but it seems the callback is never invoked.

``` clojure
(send producer record
    (reify Callback (onCompletion [_ metadata exception] (println "offset: " (:offset metadata))))
 )
```

**Comment by ragnard** [comment]
You shouldn't reify `Callback` yourself, as per the docs "Callback should be a fn of two arguments, a map as [...], and an exception. Exception will be nil if operation succeeded."

See: 
https://github.com/pingles/clj-kafka/blob/master/src/clj_kafka/new/producer.clj#L53

**Comment by manuzhang** [comment]
indeed, my mistake.
