### ISSUE TITLE
Does this breaks with clojure 1.8?

### ISSUE THREAD

**Issue by chhatanidinesh** [pingles/clj-kafka#82]

**Comment by pingles** [comment]
OTOH I think some of our teams will be using 1.8 with clj-kafka. Are you unable to use 1.8 and clj-kakfa?

**Comment by chhatanidinesh** [comment]
Yes. My consumer is not consuming any messages. Kafka console consumer at
same time works.

**Comment by pingles** [comment]
Can you reproduce the behaviour running the clj-kafka tests with `lein expectations` having updated the dependency?

**Comment by chhatanidinesh** [comment]
We got the problem. We were using very old clj-kafka and which was breaking with clojure 1.8. Using the latest clj-kafka and clojure 1.8 doesn't seems to be a problem. Thanks for your suggestions.
